# Extract frequent itemsets

เริ่มจากการหา frequent itemsets
- ใช้ dataset จากไฟล์ `Groceries_dataset.csv`
- อัพโหลดขึ้น google drive

## สร้าง DataFrame

- เรียกใช้ `pandas`

In [1]:
import pandas as pd

- อ่านไฟล์ `Groceries_dataset.csv`
groceries_df = pd.read_csv('       ')

In [2]:
groceries_df = pd.read_csv('groceries.csv')
groceries_df

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,17,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9831,1,cooking chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9832,10,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9833,4,semi-finished bread,bottled water,soda,bottled beer,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9834,5,chicken,tropical fruit,other vegetables,vinegar,shopping bags,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

*   transactions = [row[1:row[0]+1] for row in groceries_df.values]

In [3]:
transactions = [row[1:row[0]+1] for row in groceries_df.values]
# row[0] คือความยาวของ transaction, ข้อมูลจะอยู่ที่ row[1:row[0]+1]  >>  นำมาสร้างเป็น list โดย .values ให้ค่าออกมาเป็น array 2  มิติ (list of list)

## ปรับรูปแบบ transactions

transactions จะต้องอยู่ในรูปแบบของตาราง ที่แต่ละแถวแสดงการมี (True) หรือไม่มี (False) สินค้าใน 1 รายการของ transaction
- ใช้ `TransactionEncoder`  
from mlxtend.preprocessing import TransactionEncoder

In [4]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te.fit(transactions)
# fit() จะเรียนรู้ unique items ทั้งหมด ที่เจอใน transactions

t_encode = te.transform(transactions)

df = pd.DataFrame(t_encode, columns=te.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

## หา frequent itemsets

In [5]:
from mlxtend.frequent_patterns import apriori

fia = apriori(df, min_support=0.02, use_colnames=True)
fia['length'] = fia['itemsets'].apply(lambda x: len(x)) # นับจำนวน items ที่อยู่ในแต่ละ itemset
fia.sort_values('support', ascending=False)

     support                         itemsets  length
57  0.255516                     (whole milk)       1
39  0.193493               (other vegetables)       1
43  0.183935                     (rolls/buns)       1
49  0.174377                           (soda)       1
58  0.139502                         (yogurt)       1
..       ...                              ...     ...
75  0.020539        (whole milk, frankfurter)       2
60  0.020437       (bottled beer, whole milk)       2
76  0.020437  (frozen vegetables, whole milk)       2
96  0.020437      (pip fruit, tropical fruit)       2
67  0.020031       (butter, other vegetables)       2

[122 rows x 3 columns]

## หา Association rules

In [6]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(fia, metric="confidence", min_threshold=0.3)
rules.sort_values('lift', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
32,"(whole milk, other vegetables)",(root vegetables),0.074835,0.108998,0.023183,0.309783,2.842082,1.0,0.015026,1.290900,0.700572,0.144304,0.225347,0.261235
34,"(whole milk, root vegetables)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,1.0,0.013719,1.533320,0.622230,0.105751,0.347821,0.296912
17,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,1.0,0.026291,1.426693,0.622764,0.185731,0.299078,0.339789
19,(whipped/sour cream),(other vegetables),0.071683,0.193493,0.028876,0.402837,2.081924,1.0,0.015006,1.350565,0.559803,0.122203,0.259569,0.276037
35,"(whole milk, yogurt)",(other vegetables),0.056024,0.193493,0.022267,0.397459,2.054131,1.0,0.011427,1.338511,0.543633,0.097987,0.252901,0.256270
36,"(other vegetables, yogurt)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,1.0,0.011174,1.528340,0.524577,0.080485,0.345695,0.300014
4,(butter),(whole milk),0.055414,0.255516,0.027555,0.497248,1.946053,1.0,0.013395,1.480817,0.514659,0.097237,0.324697,0.302543
16,(pork),(other vegetables),0.057651,0.193493,0.021657,0.375661,1.941476,1.0,0.010502,1.291779,0.514595,0.094373,0.225874,0.243795
7,(curd),(whole milk),0.053279,0.255516,0.026131,0.490458,1.919481,1.0,0.012517,1.461085,0.505984,0.092446,0.315577,0.296363
33,"(root vegetables, other vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,1.0,0.011076,1.457687,0.501524,0.082879,0.313982,0.289999
3,(butter),(other vegetables),0.055414,0.193493,0.020031,0.361468,1.868122,1.0,0.009308,1.263065,0.491965,0.087517,0.208275,0.232494
9,(domestic eggs),(whole milk),0.063447,0.255516,0.029995,0.472756,1.850203,1.0,0.013783,1.412030,0.490649,0.103800,0.291800,0.295073
8,(domestic eggs),(other vegetables),0.063447,0.193493,0.022267,0.350962,1.813824,1.0,0.009991,1.242619,0.479074,0.094887,0.195248,0.233021
5,(citrus fruit),(other vegetables),0.082766,0.193493,0.028876,0.348894,1.803140,1.0,0.012862,1.238674,0.485603,0.116728,0.192685,0.249066
15,(pip fruit),(other vegetables),0.075648,0.193493,0.026131,0.345430,1.785237,1.0,0.011494,1.232118,0.475847,0.107531,0.188389,0.240240
25,(sausage),(rolls/buns),0.093950,0.183935,0.030605,0.325758,1.771048,1.0,0.013324,1.210344,0.480506,0.123766,0.173788,0.246074
18,(tropical fruit),(other vegetables),0.104931,0.193493,0.035892,0.342054,1.767790,1.0,0.015589,1.225796,0.485239,0.136716,0.184204,0.263775
30,(whipped/sour cream),(whole milk),0.071683,0.255516,0.032232,0.449645,1.759754,1.0,0.013916,1.352735,0.465077,0.109273,0.260757,0.287895
27,(root vegetables),(whole milk),0.108998,0.255516,0.048907,0.448694,1.756031,1.0,0.021056,1.350401,0.483202,0.154961,0.259479,0.320049
11,(frozen vegetables),(whole milk),0.048094,0.255516,0.020437,0.424947,1.663094,1.0,0.008149,1.294636,0.418855,0.072172,0.227582,0.252466
13,(margarine),(whole milk),0.058566,0.255516,0.024199,0.413194,1.617098,1.0,0.009235,1.268706,0.405348,0.083479,0.211796,0.253951
21,(yogurt),(other vegetables),0.139502,0.193493,0.043416,0.311224,1.608457,1.0,0.016424,1.170929,0.439613,0.149930,0.145977,0.267804
0,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,1.0,0.007845,1.251315,0.389597,0.074113,0.200841,0.244103
29,(tropical fruit),(whole milk),0.104931,0.255516,0.042298,0.403101,1.577595,1.0,0.015486,1.247252,0.409045,0.132950,0.198238,0.284320
31,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,1.0,0.020379,1.244132,0.422732,0.165267,0.196226,0.310432
23,(pip fruit),(whole milk),0.075648,0.255516,0.030097,0.397849,1.557043,1.0,0.010767,1.236375,0.387036,0.099966,0.191184,0.257818
2,(brown bread),(whole milk),0.064870,0.255516,0.025216,0.388715,1.521293,1.0,0.008641,1.217899,0.366435,0.085429,0.178914,0.243701
20,(other vegetables),(whole milk),0.193493,0.255516,0.074835,0.386758,1.513634,1.0,0.025394,1.214013,0.420750,0.200000,0.176286,0.339817
24,(pork),(whole milk),0.057651,0.255516,0.022166,0.384480,1.504719,1.0,0.007435,1.209520,0.355945,0.076171,0.173226,0.235614
22,(pastry),(whole milk),0.088968,0.255516,0.033249,0.373714,1.462587,1.0,0.010516,1.188729,0.347166,0.106828,0.158765,0.251919
6,(citrus fruit),(whole milk),0.082766,0.255516,0.030503,0.368550,1.442377,1.0,0.009355,1.179008,0.334375,0.099108,0.151829,0.243965
12,(fruit/vegetable juice),(whole milk),0.072293,0.255516,0.026640,0.368495,1.442160,1.0,0.008168,1.178904,0.330488,0.088454,0.151755,0.236376
10,(frankfurter),(whole milk),0.058973,0.255516,0.020539,0.348276,1.363029,1.0,0.005470,1.142330,0.283031,0.069872,0.124596,0.214329
14,(newspapers),(whole milk),0.079817,0.255516,0.027351,0.342675,1.341110,1.0,0.006957,1.132597,0.276412,0.088808,0.117073,0.224859
28,(sausage),(whole milk),0.093950,0.255516,0.029893,0.318182,1.245252,1.0,0.005887,1.091910,0.217372,0.093541,0.084173,0.217587
1,(bottled water),(whole milk),0.110524,0.255516,0.034367,0.310948,1.216940,1.0,0.006126,1.080446,0.200417,0.103617,0.074456,0.222724
26,(rolls/buns),(whole milk),0.183935,0.255516,0.056634,0.307905,1.205032,1.0,0.009636,1.075696,0.208496,0.147942,0.070369,0.264776